 <option value="">-- Select One --</option>
<option value="1">Bacolod  (BCD)</option>                             
<option value="2">Basco (Batanes) (BSO)</option>            
<option value="3">Busuanga (Coron) (USU)</option>
<option value="4">Butuan  (BXU)</option>         
<option value="5">Cagayan de Oro  (CGY)</option>        
<option value="6">Calbayog  (CYP)</option>           
<option value="7">Catarman  (CRM)</option>        
<option value="8">Caticlan (Boracay) (MPH)</option>     
<option value="9">Cebu  (CEB)</option>                        
<option value="10">Clark  (CRK)</option>                               
<option value="11">Cotabato  (CBO)</option>                            
<option value="12">Davao  (DVO)</option>                    
<option value="13">Dipolog  (DPL)</option>                
<option value="14">Dumaguete  (DGT)</option>          
<option value="15">General Santos  (GES)</option>              
<option value="16">Iloilo  (ILO)</option>             
<option value="17">Kalibo  (KLO)</option>        
<option value="18">Laoag  (LAO)</option>         
<option value="19" >Legazpi  (LGP)</option>        
<option value="20" >Manila  (MNL)</option>   
<option value="21">Masbate  (MBT)</option>        
<option value="22">Naga  (WNP)</option>          
<option value="23">Ozamiz  (OZC)</option>     
<option value="24">Puerto Princesa  (PPS)</option>       
<option value="25">Roxas  (RXS)</option>                     
<option value="26">Surigao  (SUG)</option>                     
<option value="27">Tacloban  (TAC)</option>          
<option value="28">Tagbilaran (Bohol) (TAG)</option>           
<option value="29">Tuguegarao  (TUG)</option>       
<option value="30">Zamboanga  (ZAM)</option>
